# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-07 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profie_photo',
            new_name='profile_photo',
        ),
    ]
